### PR TITLE
[checkapi] fix panic when trying to find the config Struct

### LINKED ISSUE #1029: Crash when running checkapi
### Component

_No response_

### Bug Description

In the otel-collector repo:

```
checkapi -folder . -config .checkapi.yaml
panic: [memorylimiterextension] Unsupported type *ast.CallExpr

goroutine 1 [running]:
go.opentelemetry.io/build-tools/checkapi/internal.readFile({0x0, 0x0, 0x0}, 0x140000f88c0, 0x14000157000)
        go.opentelemetry.io/build-tools/checkapi@v0.24.0/internal/ast.go:244 +0x884
go.opentelemetry.io/build-tools/checkapi/internal.Read({0x14000356450, 0x20}, {0x0, 0x0, 0x0}, {0x1400006c2a0, 0x2, 0x5?})
        go.opentelemetry.io/build-tools/checkapi@v0.24.0/internal/ast.go:117 +0x244
main.walkFolder({{0x14000024280, 0x1, 0x1}, {0x1400006c2a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...)
        go.opentelemetry.io/build-tools/checkapi@v0.24.0/main.go:84 +0x84
main.run.func1({0x14000356450, 0x27}, {0x10221f588?, 0x140000ef520?}, {0x14000157a78?, 0x10212f0cc?})
        go.opentelemetry.io/build-tools/checkapi@v0.24.0/main.go:68 +0x2b4
path/filepath.walk({0x14000356450, 0x27}, {0x10221f588, 0x140000ef520}, 0x14000157e90)
        path/filepath/path.go:345 +0xc8
path/filepath.walk({0x1400001c9e0, 0x20}, {0x10221f588, 0x140000eeea0}, 0x14000157e90)
        path/filepath/path.go:369 +0x1d0
path/filepath.walk({0x1400039be80, 0x9}, {0x10221f588, 0x140003c5c70}, 0x14000157e90)
        path/filepath/path.go:369 +0x1d0
path/filepath.walk({0x16dd7f62d, 0x1}, {0x10221f588, 0x1400007e820}, 0x14000157e90)
        path/filepath/path.go:369 +0x1d0
path/filepath.Walk({0x16dd7f62d, 0x1}, 0x1400012be90)
        path/filepath/path.go:427 +0x6c
main.run({0x16dd7f62d, 0x1}, {0x16dd7f637?, 0x1021aa8f7?})
        go.opentelemetry.io/build-tools/checkapi@v0.24.0/main.go:46 +0xdc
main.main()
        go.opentelemetry.io/build-tools/checkapi@v0.24.0/main.go:30 +0xec
make: *** [checkapi] Error 2
```

### Steps To Reproduce

Upgrade checkapi to 0.24.0 and run `make checkapi` in the opentelemetry-collector.

### Expected Behavior

Not to crash

### PR DESCRIPTION
**Pull request by atoulme**
Fixes #1029

### CODE REVIEW

File: checkapi/internal/ast.go [hunk 1]
```diff
@@ -254,6 +233,45 @@ func readFile(ignoredFunctions []string, f *ast.File, result *API) {
 	}
 }
 
+func extractFunctionReturnType(fn *ast.FuncDecl) string {
+	if ret, ok := fn.Body.List[len(fn.Body.List)-1].(*ast.ReturnStmt); ok {
+		if len(ret.Results) == 1 {
```
Comment (mx-psi) [inline checkapi/internal/ast.go:238]: Why not `if !<condition> then bail out` instead of indenting everything?

**Review by dmathieu — APPROVED** [review]
