### PR TITLE
[crosslink] Ignore known zap.logger.sync() errors

### LINKED ISSUE #190: crosslink error on macOs
```bash
$ crosslink --root=/Users/lazy/github/opentelemetry-collector --prune
failed to sync logger:  sync /dev/stderr: inappropriate ioctl for device 
```

The tool does it job, but prints an annoying error.

### PR DESCRIPTION
**Pull request by bryan-aguilar**
Move logger.sync() method call to cobras `postRunSetup` and ignore `ENOTTY` error produced on unix systems. 

Fixes #190

### CODE REVIEW

File: crosslink/cmd/root.go [hunk 1]
```diff
@@ -71,13 +73,22 @@ func newCommandConfig() *commandConfig {
 
 	}
 
+	postRunSetup := func(cmd *cobra.Command, args []string) error {
+		err := c.runConfig.Logger.Sync()
+		if err != nil && !errors.Is(err, syscall.ENOTTY) {
```
[the remark this answers is not in the document]
Comment (bryan-aguilar) [reply crosslink/cmd/root.go:78]: Great suggestion. Thanks for pointing me in that direction

File: .chloggen/crosslinkErrSup.yaml [hunk 2]
```diff
@@ -0,0 +1,16 @@
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: enhancement
+
+# The name of the component, or a single word describing the area of concern, (e.g. crosslink)
+component: crosslink
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Ignore ENOTTY error produced by zaps logger.sync() method
```
Comment (mx-psi) [inline .chloggen/crosslinkErrSup.yaml:8]: The changelog entry now needs an update

Comment (bryan-aguilar) [reply .chloggen/crosslinkErrSup.yaml]: Good catch, thanks for the reminder. Updated.

**Review by mx-psi — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]
